In [1]:
import numpy as np
import pandas as pd

def parse_txt(file):
    with open(file, 'r') as f:
        lines = f.readlines()
    lines = [line.strip() for line in lines if line.strip() != '' and line.strip() != '\n']
    return lines

parsed_lines = parse_txt('data/output.txt')

In [2]:
uniform_volume_points_occupancies = []
boundary_points_occupancies = []

for i, el in enumerate(parsed_lines):
    if el.startswith("Uniform volume points occupancy"):
        uniform_volume_points_occupancies.append(float(el.split(":")[1].strip()))
    elif el.startswith("Boundary points occupancy"):
        boundary_points_occupancies.append(float(el.split(":")[1].strip()))

In [3]:
np.mean(boundary_points_occupancies)

0.947513674664074

In [4]:
import numpy as np
np.mean(uniform_volume_points_occupancies)

0.9718048945576194

In [5]:
df = pd.DataFrame({'boundary_points_occupancies': boundary_points_occupancies, 'uniform_volume_points_occupancies': uniform_volume_points_occupancies})
df

    boundary_points_occupancies  uniform_volume_points_occupancies
0                      0.940545                           0.977314
1                      0.988376                           0.994487
2                      0.995996                           0.997673
3                      0.995179                           0.997671
4                      0.969413                           0.988562
5                      0.966125                           0.997899
6                      0.992435                           0.997180
7                      0.966200                           0.987340
8                      0.983255                           0.996714
9                      0.502176                           0.511816
10                     0.946845                           0.970765
11                     0.984595                           0.980887
12                     0.993739                           0.998177
13                     0.970581                           0.995010
14                     0.989650                           0.995008
15                     0.722816                           0.785892
16                     0.898289                           0.963528
17                     0.891426                           0.963040
18                     0.760907                           0.922119
19                     0.977570                           0.994343
20                     0.904288                           0.968585
21                     0.989387                           0.992412
22                     0.991822                           0.998199
23                     0.993023                           0.997182
24                     0.990122                           0.997235
25                     0.990583                           0.996792
26                     0.871468                           0.945416
27                     0.967322                           0.994869
28                     0.911689                           0.964107
29                     0.991128                           0.993648
30                     0.995657                           0.993671
31                     0.994792                           0.999510
32                     0.898708                           0.973485
33                     0.902539                           0.966686
34                     0.986457                           0.991722
35                     0.990142                           0.991242
36                     0.804370                           0.890057
37                     0.988209                           0.993673
38                     0.994173                           0.998167
39                     0.991114                           0.997431
40                     0.990876                           0.996257
41                     0.990945                           0.997346
42                     0.993472                           0.997706
43                     0.916528                           0.986626
44                     0.995433                           0.999777
45                     0.993434                           0.995715
46                     0.949546                           0.970846
47                     0.988032                           0.996319
48                     0.980647                           0.991711
49                     0.993659                           0.998426

In [6]:
df.to_csv('f1_occupancies.csv', index=False)